backend:
  name: git-gateway
  branch: main
media_folder: assets/img
public_folder: /img
collections:
  - name: 'pages'
    label: 'Pages'
    folder: "content"
    create: true
    editor:
      preview: false
    nested:
      depth: 100 # max depth to show in the collection tree
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Menu Weight", name: "weight", widget: "number", step: 1, default: 0}
      - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              hint: 'A short description of what the page is about.  This will only display in search results or in previews of the link to this page.', required: false
            }
      
      - {label: "Body", name: "body", widget: "markdown", modes: ['raw'], hint: 'For an aside, copy/paste this: {{< aside >}}âœ¨{{< /aside >}} and replace the stars with text'}
      - {label: "Date", name: "date", widget: "datetime"}
      - { name: "preview_image", label: "Preview Image", widget: "object", fields: [{label: "Image", name: image, widget: "image", hint: 'This will display in previews when this page is shared on social media.  If it is larger than 1200px wide, it will be scaled and cropped to fill the dimensions 1200px by 630px.  If it is smaller or equal to 1200px wide, it will be cropped to be a square.', required: false}, {label: "Alt Text", name: "alt", widget: "string", required: false}]}
      - { name: "preview_audio", label: "Preview Audio URL", widget: "string", required: false}
      - {label: "Translation Key", name: "translationKey", widget: "string", hint: "Two pages with the same translation key will be considered different translations of the same content", required: false}
      - {label: "Hide Footer", name: "hide_footer", widget: "boolean", default: false, required: false}
      - {label: "Menu", name: "menu", widget: "select", options: [ { label: "Main", value: "main" }, { label: "None", value: "none" } ], default: "main"
      }
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }
  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false
    files:
      - file: 'config.toml'
        label: 'Settings'
        name: 'settings'
        fields:
        - name: "params"
          label: "Params"
          widget: "object"
          fields:
            - {label: "Theme Vars 1", name: "themeVars1", widget: "text", required: true}
            - {label: "Theme Vars 2", name: "themeVars2", widget: "text", required: true}
            - {label: "Theme Vars 3", name: "themeVars3", widget: "text", required: true}
            - {label: "Theme Vars 4", name: "themeVars4", widget: "text", required: true} 
            - {label: "Hide Header", name: "hideHeader", widget: "boolean", default: false, required: false}
            - {label: "Home Link Text", name: "homeLinkText", widget: "string", required: false}  